version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/pandahacker/express-walkin-backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "4000"
    command: "npm start"
